### ISSUE TITLE
Per-site settings

### ISSUE THREAD

**Issue by reinerh** [M-Reimer/languageswitch#4] opened 2020-04-04 13:48 UTC
Thanks for the nice simple addon.
It would be good if you could also have different settings depending on the site you are visiting.
For most sites I would like to keep the default language, but some I'd like to read in a different language.
I'm not sure if it would be within scope of this addon, it's just a suggestion. :-)

**Comment by M-Reimer** [comment] 2020-09-22 17:44
There is a good chance that this is out of scope. "Per site settings" actually is a pretty big task and would make the whole Add-on way more complex. My goal was to provide a simple switching menu primarily for web developers to check if their automatic language detection works as intended. Most websites allow to override this browser language anyways.

There are per-site header modification Add-ons on AMO. Maybe this one will fit your needs:
https://addons.mozilla.org/firefox/addon/http-header-mangler/

**Comment by cryptomilk** [comment] 2020-10-15 08:07
I think per-site settings would make this addon really useful!

**Comment by M-Reimer** [comment] 2020-10-15 11:23
The Add-on is meant for checking language switching and primarily targets web developers.

All web applications that I know have a language setting somewhere. Often in the user profile.

And your primary language should be set directly in Firefox anyway. No Add-on is needed for that. You find this in the Firefox preferences directly on the "General" category if you scroll down to "Language". Click "Choose..." there.

I'll have a deeper look into this topic sometime later to find out how much work it would be to add this, but there is a very strong tendency that this bug will be closed as "out of scope".

**Comment by M-Reimer** [comment] 2021-09-03 13:36
Adding any way to make something that is **not** a global setting change would **heavily** increase the codebase of my Add-on.

The goal of **this** Add-on is to provide a global switch of the preferred language which is communicated to websites. It was never the plan to provide any kind of "per site" or "per tab" switching. With a functionality like this in mind the whole Add-on would have to be developed in a different way, so to make something like this it would be better to start from scratch and create the whole backend with either "per site" or "per tab" switching in mind.

AND MOST IMPORTANT: I don't plan to do this.

**Closed by M-Reimer** 2021-09-03 13:36 UTC
Labels: later
