### ISSUE TITLE
Trainline.com/fr top menu hidden

### ISSUE THREAD

**Issue by fanfu** [M-Reimer/languageswitch#9] opened 2020-09-27 16:10 UTC
Hi,

I noticed an issue on the following website https://www.thetrainline.com/fr It may affect other websites.
When logged in on the website with the addon activated, the top menu is no more visible. 
![2020-09_trainline_locale-sw1](https://user-images.githubusercontent.com/528538/94369823-50a1e080-00ec-11eb-821a-017f8829c8b8.png)

As the addon is deactivated and the page reloaded (CTRL F5), the menu is visible again
![2020-09_trainline_locale-sw2](https://user-images.githubusercontent.com/528538/94369824-513a7700-00ec-11eb-9a93-5b26890f7148.png)

**Comment by M-Reimer** [comment] 2020-09-27 16:32
What happens if you set to the language to "Default" in my Add-on?

**Comment by M-Reimer** [comment] 2020-09-29 16:03
Tried it (even while logged in which seems to be where you had problems) and can't reproduce your problem. The top right menu comes with a delay but it is displayed with all settings I tried.
So currently all I can do is close this one as I can't reproduce the problem.
Can you try again just to be sure it really depends on languageswitch being installed and if there are language settings where the problem does not occur?

**Comment by M-Reimer** [comment] 2020-10-06 14:09
No more feedback and I can't reproduce the problem. Please reopen if the problem still exists.

**Closed by M-Reimer** 2020-10-06 14:09 UTC
Labels: help wanted
